title: ths dashboard
description: This is the dashboard for the THS investigation
theme: just-the-docs

url: https://moisesrobles-04.github.io/ths-dashboard

aux_links:
  Template Repository: https://github.com/moisesrobles-04/ths-dashboard
  
